### ISSUE TITLE
InvalidArgumentException View [Users] not found. 

### ISSUE THREAD

**Issue by RobertoBochet** [billyboy35/WebErpMesv2#10]
**Describe the bug**
In the page `/users` and some other it appears the error

```
InvalidArgumentException
View [Users] not found. 
```
With suggestion
```
 Users was not found.

Did you mean users?
```
Probably it is correlated to the other issues #7 #9  

**To Reproduce**
1. Create `.env` file
1. `docker-compose up`
1. Go to `http://127.0.0.1:45060/users`

**Comment by SMEWebify** [comment]
nice work, thank you
