### ISSUE TITLE
`composer.json` property `name` should be lowercase

### ISSUE THREAD

**Issue by RobertoBochet** [billyboy35/WebErpMesv2#11]
**Describe the bug**
[Since the composer version 2.0 the property `name` in `composer.json` should be lowercase](https://getcomposer.org/doc/04-schema.md#name)

This error prevents to run `composer i` with composer version greater than `2.0`

**Comment by SMEWebify** [comment]
Fixed

**Comment by RobertoBochet** [comment]
Thanks!
